<script lang="ts">
  import { onMount } from 'svelte';
  import { Check, Copy, Image as ImageIcon, LoaderCircle, RefreshCw, Trash2 } from 'lucide-svelte';
  import { api } from '$lib/api';
  import CmsImageField from '$lib/components/CmsImageField.svelte';
  type Asset={id:string;originalName:string;width:number;height:number;byteSize:number;orientation:string;purpose?:string;createdAt:string;format:string};
  let items:Asset[]=$state([]),loading=$state(true),error=$state(''),notice=$state(''),uploaded=$state('');
  const headers=()=>({authorization:`Bearer ${localStorage.getItem('bp_token')}`});
  const url=(item:Asset)=>`${import.meta.env.PUBLIC_API_URL||'http://localhost:4000/api'}/media/${item.id}.${item.format}`;
  async function load(){loading=true;error='';try{items=await api<Asset[]>('/admin/media',{headers:headers()})}catch(e){error=e instanceof Error?e.message:'Unable to load media'}finally{loading=false}}
  async function remove(item:Asset){if(!confirm(`Delete ${item.originalName}? Images in use cannot be deleted.`))return;try{await api(`/admin/media/${item.id}`,{method:'DELETE',headers:headers()});items=items.filter(value=>value.id!==item.id);notice='Unused image deleted.'}catch(e){error=e instanceof Error?e.message:'Unable to delete image'}}
  async function copy(item:Asset){await navigator.clipboard.writeText(url(item));notice='Image URL copied.'}
  function uploadedImage(value:string){uploaded=value;notice='Image optimized and stored. It is ready to use.';load()}
  onMount(load);
</script>
<svelte:head><title>Media Library — Bengal Port Admin</title></svelte:head>
<main class="media-page"><header><div><span>CONTENT OPERATIONS</span><h1>Media library</h1><p>Optimized WebP assets stored directly in PostgreSQL.</p></div><button onclick={load}><RefreshCw size={17}/> Refresh</button></header>{#if error}<div class="notice error" role="alert">{error}</div>{/if}{#if notice}<div class="notice success"><Check size={16}/>{notice}</div>{/if}<section class="upload-card"><CmsImageField label="Upload a reusable image" value={uploaded} purpose="media library" recommendation="Choose the orientation required by the destination. The CMS gives section-specific recommendations when selected there." onchange={uploadedImage}/></section>{#if loading}<div class="loading"><LoaderCircle class="spin"/> Loading media…</div>{:else if !items.length}<div class="empty"><ImageIcon/><h2>No stored media yet</h2><p>Upload an image above or from any CMS image field.</p></div>{:else}<section class="grid">{#each items as item}<article><div class:portrait={item.orientation==='portrait'} class="thumb"><img src={url(item)} alt={item.originalName}/><span>{item.orientation}</span></div><div class="copy"><h2>{item.originalName}</h2><p>{item.width}×{item.height} · {Math.max(1,Math.round(item.byteSize/1024))} KB · WebP</p><small>{item.purpose||'General media'} · {new Date(item.createdAt).toLocaleDateString()}</small><div><button onclick={()=>copy(item)}><Copy size={15}/> Copy URL</button><button class="delete" onclick={()=>remove(item)}><Trash2 size={15}/> Delete</button></div></div></article>{/each}</section>{/if}</main>
<style>.media-page{padding:clamp(1rem,4vw,3rem);max-width:96rem;margin:auto}.media-page>header{display:flex;flex-direction:column;align-items:flex-start;gap:1rem;margin-bottom:1.5rem}.media-page>header span{font-size:.72rem;letter-spacing:.13em;font-weight:800;color:var(--gold-deep)}h1{font-size:clamp(2rem,7vw,3rem);color:var(--heading);letter-spacing:-.04em;margin:.35rem 0}header p{color:var(--muted);margin:0}button{min-height:2.75rem;border:1px solid #d8dfe4;border-radius:.65rem;background:#fff;color:var(--heading);display:inline-flex;align-items:center;justify-content:center;gap:.45rem;padding:.6rem .8rem;cursor:pointer}.upload-card{background:#fff;border:1px solid #dfe5e8;border-radius:1rem;padding:clamp(1rem,3vw,1.6rem);margin-bottom:1.2rem}.notice{display:flex;gap:.5rem;padding:.8rem 1rem;border-radius:.7rem;margin-bottom:.8rem}.error{background:#fff0f0;color:#8e2d2d}.success{background:#eaf7ef;color:#276541}.loading,.empty{min-height:18rem;display:grid;place-items:center;align-content:center;gap:.6rem;color:var(--muted);text-align:center}.grid{display:grid;grid-template-columns:1fr;gap:1rem}.grid article{background:#fff;border:1px solid #dfe5e8;border-radius:.9rem;overflow:hidden}.thumb{aspect-ratio:16/10;position:relative;background:#e9edef;overflow:hidden}.thumb img{width:100%;height:100%;object-fit:cover}.thumb span{position:absolute;left:.65rem;bottom:.65rem;background:#102640dc;color:#fff;padding:.3rem .45rem;border-radius:.4rem;font-size:.68rem;text-transform:capitalize}.copy{padding:1rem}.copy h2{font-size:.95rem;color:var(--heading);overflow-wrap:anywhere;margin:0 0 .4rem}.copy p,.copy small{display:block;color:var(--muted);font-size:.75rem;line-height:1.5;margin:0}.copy>div{display:flex;flex-wrap:wrap;gap:.5rem;margin-top:.9rem}.delete{color:#993d3d}.spin{animation:spin .8s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}@media(min-width:40rem){.media-page>header{flex-direction:row;justify-content:space-between;align-items:flex-start}.grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(min-width:64rem){.grid{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(prefers-reduced-motion:reduce){.spin{animation:none}}</style>
