import type { FastifyPluginAsync } from "fastify";
import bcrypt from "bcryptjs";
import crypto from "node:crypto";
import { OAuth2Client } from "google-auth-library";
import { z } from "zod";
import { prisma } from "../lib/prisma.js";
import { sendAuthCode } from "../lib/email.js";

const password = z.string().min(8).max(128).regex(/[a-z]/).regex(/[A-Z]/).regex(/\d/);
const google = new OAuth2Client(process.env.GOOGLE_CLIENT_ID);
const publicUser = (u:any) => ({ id:u.id,name:u.name,email:u.email,phone:u.phone,role:u.role,avatarUrl:u.avatarUrl,emailVerified:Boolean(u.emailVerifiedAt),twoFactorEnabled:u.twoFactorEnabled,provider:u.googleId?"google":"password" });

const routes:FastifyPluginAsync=async app=>{
  app.addHook("onRequest",app.rateLimit({max:20,timeWindow:"1 minute"}));
  const issue=async(user:any,purpose:"VERIFY_EMAIL"|"LOGIN_2FA"|"RESET_PASSWORD")=>{
    await prisma.authCode.updateMany({where:{userId:user.id,purpose,consumedAt:null},data:{consumedAt:new Date()}});
    const code=String(crypto.randomInt(100000,1000000));
    const challenge=await prisma.authCode.create({data:{userId:user.id,purpose,codeHash:await bcrypt.hash(code,10),expiresAt:new Date(Date.now()+600_000)}});
    const delivered=await sendAuthCode(user.email,user.name,code,purpose);
    return {challengeId:challenge.id,delivered,...(!delivered&&process.env.NODE_ENV!=="production"?{developmentCode:code}:{})};
  };
  const consume=async(challengeId:string,code:string,purpose:"VERIFY_EMAIL"|"LOGIN_2FA"|"RESET_PASSWORD")=>{
    const challenge=await prisma.authCode.findUnique({where:{id:challengeId},include:{user:true}});
    if(!challenge||challenge.purpose!==purpose||challenge.consumedAt||challenge.expiresAt<new Date()||challenge.attempts>=5)return null;
    if(!await bcrypt.compare(code,challenge.codeHash)){await prisma.authCode.update({where:{id:challenge.id},data:{attempts:{increment:1}}});return null;}
    await prisma.authCode.update({where:{id:challenge.id},data:{consumedAt:new Date()}}); return challenge.user;
  };
  const session=(user:any)=>({token:app.jwt.sign({sub:user.id,role:user.role},{expiresIn:"7d"}),user:publicUser(user)});

  app.post("/register",async(req,reply)=>{const p=z.object({name:z.string().trim().min(2).max(100),email:z.string().email(),phone:z.string().trim().min(7).max(30).optional(),password}).safeParse(req.body);if(!p.success)return reply.code(400).send({error:{code:"VALIDATION_ERROR",message:"Use a valid email and a password with uppercase, lowercase and a number."}});if(await prisma.user.findUnique({where:{email:p.data.email.toLowerCase()}}))return reply.conflict("Email already registered");const user=await prisma.user.create({data:{name:p.data.name,email:p.data.email.toLowerCase(),phone:p.data.phone,passwordHash:await bcrypt.hash(p.data.password,12)}});return reply.code(201).send({data:{...(await issue(user,"VERIFY_EMAIL")),email:user.email}})});
  app.post("/verify-email",async(req,reply)=>{const p=z.object({challengeId:z.string(),code:z.string().length(6)}).safeParse(req.body);if(!p.success)return reply.badRequest("Invalid verification code");const user=await consume(p.data.challengeId,p.data.code,"VERIFY_EMAIL");if(!user)return reply.unauthorized("The code is invalid or expired");const verified=await prisma.user.update({where:{id:user.id},data:{emailVerifiedAt:new Date(),lastLoginAt:new Date()}});return {data:session(verified)}});
  app.post("/resend-verification",async(req,reply)=>{const p=z.object({email:z.string().email()}).safeParse(req.body);if(!p.success)return reply.badRequest("Invalid email");const user=await prisma.user.findUnique({where:{email:p.data.email.toLowerCase()}});if(!user||user.emailVerifiedAt)return {data:{accepted:true}};return {data:{accepted:true,...await issue(user,"VERIFY_EMAIL")}}});
  app.post("/login",async(req,reply)=>{const p=z.object({email:z.string().email(),password:z.string()}).safeParse(req.body);if(!p.success)return reply.unauthorized("Invalid credentials");const user=await prisma.user.findUnique({where:{email:p.data.email.toLowerCase()}});if(!user||!user.passwordHash||!await bcrypt.compare(p.data.password,user.passwordHash))return reply.unauthorized("Invalid credentials");if(!user.emailVerifiedAt){const c=await issue(user,"VERIFY_EMAIL");return reply.code(403).send({error:{code:"EMAIL_NOT_VERIFIED",message:"Verify your email before signing in.",details:{...c,email:user.email}}})}if(user.twoFactorEnabled)return {data:{requiresTwoFactor:true,...await issue(user,"LOGIN_2FA")}};await prisma.user.update({where:{id:user.id},data:{lastLoginAt:new Date()}});return {data:session(user)}});
  app.post("/verify-2fa",async(req,reply)=>{const p=z.object({challengeId:z.string(),code:z.string().length(6)}).safeParse(req.body);if(!p.success)return reply.badRequest("Invalid code");const user=await consume(p.data.challengeId,p.data.code,"LOGIN_2FA");if(!user)return reply.unauthorized("The code is invalid or expired");await prisma.user.update({where:{id:user.id},data:{lastLoginAt:new Date()}});return {data:session(user)}});
  app.post("/forgot-password",async(req,reply)=>{const p=z.object({email:z.string().email()}).safeParse(req.body);if(!p.success)return reply.badRequest("Invalid email");const user=await prisma.user.findUnique({where:{email:p.data.email.toLowerCase()}});return {data:{accepted:true,...(user?.passwordHash?await issue(user,"RESET_PASSWORD"):{})}}});
  app.post("/reset-password",async(req,reply)=>{const p=z.object({challengeId:z.string(),code:z.string().length(6),password}).safeParse(req.body);if(!p.success)return reply.badRequest("Invalid reset details");const user=await consume(p.data.challengeId,p.data.code,"RESET_PASSWORD");if(!user)return reply.unauthorized("The code is invalid or expired");await prisma.user.update({where:{id:user.id},data:{passwordHash:await bcrypt.hash(p.data.password,12)}});return {data:{success:true}}});
  app.post("/google",async(req,reply)=>{if(!process.env.GOOGLE_CLIENT_ID)return reply.serviceUnavailable("Google sign-in is not configured");const p=z.object({credential:z.string().min(20)}).safeParse(req.body);if(!p.success)return reply.badRequest("Missing Google credential");const ticket=await google.verifyIdToken({idToken:p.data.credential,audience:process.env.GOOGLE_CLIENT_ID});const payload=ticket.getPayload();if(!payload?.sub||!payload.email||!payload.email_verified)return reply.unauthorized("Google account could not be verified");let user=await prisma.user.findFirst({where:{OR:[{googleId:payload.sub},{email:payload.email.toLowerCase()}]}});user=user?await prisma.user.update({where:{id:user.id},data:{googleId:payload.sub,avatarUrl:payload.picture||user.avatarUrl,emailVerifiedAt:user.emailVerifiedAt||new Date(),lastLoginAt:new Date()}}):await prisma.user.create({data:{name:payload.name||payload.email.split("@")[0],email:payload.email.toLowerCase(),googleId:payload.sub,avatarUrl:payload.picture,emailVerifiedAt:new Date(),lastLoginAt:new Date()}});return {data:session(user)}});
  app.get("/me",{preHandler:app.authenticate},async(req:any)=>{const user=await prisma.user.findUniqueOrThrow({where:{id:req.user.sub}});return {data:publicUser(user)}});
  app.get("/me/activity",{preHandler:app.authenticate},async(req:any)=>{const [enquiries,applications,payments]=await Promise.all([prisma.enquiry.findMany({where:{userId:req.user.sub},orderBy:{createdAt:"desc"}}),prisma.application.findMany({where:{userId:req.user.sub},orderBy:{createdAt:"desc"}}),prisma.payment.findMany({where:{userId:req.user.sub},include:{receipt:true},orderBy:{createdAt:"desc"}})]);return {data:{enquiries,applications,payments}}});
  app.patch("/me",{preHandler:app.authenticate},async(req:any,reply)=>{const p=z.object({name:z.string().trim().min(2).max(100),phone:z.string().trim().min(7).max(30).nullable().optional()}).safeParse(req.body);if(!p.success)return reply.badRequest("Invalid profile details");const user=await prisma.user.update({where:{id:req.user.sub},data:p.data});return {data:publicUser(user)}});
  app.post("/change-password",{preHandler:app.authenticate},async(req:any,reply)=>{const p=z.object({currentPassword:z.string(),newPassword:password}).safeParse(req.body);if(!p.success)return reply.badRequest("Invalid password details");const user=await prisma.user.findUniqueOrThrow({where:{id:req.user.sub}});if(!user.passwordHash||!await bcrypt.compare(p.data.currentPassword,user.passwordHash))return reply.unauthorized("Current password is incorrect");await prisma.user.update({where:{id:user.id},data:{passwordHash:await bcrypt.hash(p.data.newPassword,12)}});return {data:{success:true}}});
  app.post("/2fa",{preHandler:app.authenticate},async(req:any,reply)=>{const p=z.object({enabled:z.boolean(),password:z.string()}).safeParse(req.body);if(!p.success)return reply.badRequest("Invalid request");const user=await prisma.user.findUniqueOrThrow({where:{id:req.user.sub}});if(!user.passwordHash)return reply.badRequest("Email 2FA applies to password accounts only");if(!await bcrypt.compare(p.data.password,user.passwordHash))return reply.unauthorized("Password is incorrect");const updated=await prisma.user.update({where:{id:user.id},data:{twoFactorEnabled:p.data.enabled}});return {data:publicUser(updated)}});
};
export default routes;
