import type { FastifyPluginAsync } from 'fastify'; import { prisma } from '../lib/prisma.js'; import { enquirySchema,applicationSchema } from '../lib/schemas.js'; import { defaultHomeContent } from '../lib/home-content.js'; import {defaultBusinessContent} from '../lib/business-content.js'; import {defaultEducationContent,defaultHealthcareContent} from '../lib/division-content.js';
const routes:FastifyPluginAsync=async app=>{
 const optionalUser=async(req:any)=>{if(!req.headers.authorization)return undefined;try{await req.jwtVerify();return req.user?.sub as string}catch{return undefined}};
 app.get('/health',async()=>({data:{status:'ok'}}));
 app.get('/media/:asset',async(req,reply)=>{const assetParam=(req.params as {asset:string}).asset;const id=assetParam.replace(/\.(webp|avif)$/i,'');const asset=await prisma.mediaAsset.findUnique({where:{id}});if(!asset)return reply.notFound('Image not found');const etag=`\"${asset.id}-${asset.byteSize}\"`;if(req.headers['if-none-match']===etag)return reply.code(304).send();return reply.header('Content-Type',asset.mimeType).header('Content-Length',String(asset.byteSize)).header('Cache-Control','public, max-age=31536000, immutable').header('ETag',etag).header('X-Content-Type-Options','nosniff').send(asset.data)});
 app.get('/content/home',async()=>{const page=await prisma.pageContent.findUnique({where:{slug:'home'}});return {data:page?.published?{content:page.content,revision:page.revision,updatedAt:page.updatedAt}:{content:defaultHomeContent,revision:0,updatedAt:null}}});
 app.get('/content/business',async()=>{const page=await prisma.pageContent.findUnique({where:{slug:'business'}});return {data:page?.published?{content:page.content,revision:page.revision,updatedAt:page.updatedAt}:{content:defaultBusinessContent,revision:0,updatedAt:null}}});
 app.get('/content/education',async()=>{const page=await prisma.pageContent.findUnique({where:{slug:'education'}});return {data:page?.published?{content:page.content,revision:page.revision,updatedAt:page.updatedAt}:{content:defaultEducationContent,revision:0,updatedAt:null}}});
 app.get('/content/healthcare',async()=>{const page=await prisma.pageContent.findUnique({where:{slug:'healthcare'}});return {data:page?.published?{content:page.content,revision:page.revision,updatedAt:page.updatedAt}:{content:defaultHealthcareContent,revision:0,updatedAt:null}}});
 app.get('/opportunities',async req=>{const q=req.query as any;const where:any={published:true};if(q.category)where.category=q.category;if(q.country)where.country=q.country;if(q.search)where.OR=[{title:{contains:q.search,mode:'insensitive'}},{description:{contains:q.search,mode:'insensitive'}}];return {data:await prisma.opportunity.findMany({where,orderBy:{createdAt:'desc'}})}});
 app.get('/opportunities/:slug',async(req,reply)=>{const item=await prisma.opportunity.findUnique({where:{slug:(req.params as any).slug}});return item?{data:item}:reply.notFound('Opportunity not found')});
 app.get('/suppliers',async()=>({data:await prisma.supplier.findMany({orderBy:[{featured:'desc'},{createdAt:'desc'}]})}));
 app.get('/factories',async()=>({data:await prisma.factory.findMany({orderBy:[{featured:'desc'},{createdAt:'desc'}]})}));
 app.get('/education',async()=>({data:await prisma.institution.findMany({include:{programs:true}})}));
 app.get('/healthcare',async()=>({data:await prisma.hospital.findMany({include:{services:true}})}));
 app.post('/enquiries',async(req,reply)=>{const parsed=enquirySchema.safeParse(req.body);if(!parsed.success)return reply.code(400).send({error:{code:'VALIDATION_ERROR',message:'Please check the enquiry fields',details:parsed.error.flatten()}});const userId=await optionalUser(req);const data=await prisma.enquiry.create({data:{...parsed.data,email:parsed.data.email||null,details:parsed.data.details as any,userId}});return reply.code(201).send({data})});
 app.post('/applications',async(req,reply)=>{const parsed=applicationSchema.safeParse(req.body);if(!parsed.success)return reply.code(400).send({error:{code:'VALIDATION_ERROR',message:'Please check the application fields',details:parsed.error.flatten()}});const reference=`BP-${Date.now().toString().slice(-8)}`;const userId=await optionalUser(req);const data=await prisma.application.create({data:{...parsed.data,details:parsed.data.details as any,reference,userId}});return reply.code(201).send({data})});
}; export default routes;

