<script lang="ts">
  import { onMount } from "svelte"; import { goto } from "$app/navigation"; import { api } from "$lib/api"; import { Check, KeyRound, LogOut, Save, ShieldCheck, UserRound } from "lucide-svelte";
  let user:any=null,loading=true,saving=false,error="",notice="",name="",phone="",currentPassword="",newPassword="",confirm="",securityPassword="";
  const token=()=>localStorage.getItem("bp_token")||""; const headers=()=>({authorization:`Bearer ${token()}`});
  onMount(async()=>{if(!token())return goto("/login?next=/profile");try{user=await api("/auth/me",{headers:headers()});name=user.name;phone=user.phone||""}catch{logout()}finally{loading=false}});
  function logout(){localStorage.removeItem("bp_token");localStorage.removeItem("bp_user");goto("/login")}
  async function saveProfile(){saving=true;error=notice="";try{user=await api("/auth/me",{method:"PATCH",headers:headers(),body:JSON.stringify({name,phone:phone||null})});localStorage.setItem("bp_user",JSON.stringify(user));notice="Profile saved."}catch(e){error=e instanceof Error?e.message:"Could not save"}finally{saving=false}}
  async function changePassword(){error=notice="";if(newPassword!==confirm){error="New passwords do not match.";return}saving=true;try{await api("/auth/change-password",{method:"POST",headers:headers(),body:JSON.stringify({currentPassword,newPassword})});currentPassword=newPassword=confirm="";notice="Password changed successfully."}catch(e){error=e instanceof Error?e.message:"Could not change password"}finally{saving=false}}
  async function toggle2fa(){saving=true;error=notice="";try{user=await api("/auth/2fa",{method:"POST",headers:headers(),body:JSON.stringify({enabled:!user.twoFactorEnabled,password:securityPassword})});securityPassword="";notice=`Two-factor authentication ${user.twoFactorEnabled?"enabled":"disabled"}.`}catch(e){error=e instanceof Error?e.message:"Could not update security"}finally{saving=false}}
</script>
<svelte:head><title>My Profile — Bengal Port</title></svelte:head>
<section class="profile-hero"><div class="wrap"><span>MY BENGAL PORT</span><h1>Account & security</h1><p>Manage your personal details and protect your account.</p></div></section>
<section class="profile-page"><div class="wrap">{#if loading}<div class="loading">Loading your account…</div>{:else if user}<header class="identity"><div class="avatar">{#if user.avatarUrl}<img src={user.avatarUrl} alt=""/>{:else}{user.name.slice(0,1).toUpperCase()}{/if}</div><div><h2>{user.name}</h2><p>{user.email}</p><span><Check/> Verified account · {user.provider==="google"?"Google":"Email and password"}</span></div><button onclick={logout}><LogOut/> Sign out</button></header>
    {#if notice}<div class="notice success"><Check/>{notice}</div>{/if}{#if error}<div class="notice error" role="alert">{error}</div>{/if}
    <div class="settings"><article><header><UserRound/><div><h2>Personal information</h2><p>Used to identify your applications and enquiries.</p></div></header><form onsubmit={(e)=>{e.preventDefault();saveProfile()}}><label><span>Full name</span><input bind:value={name} autocomplete="name" required/></label><label><span>Email address</span><input value={user.email} disabled/></label><label><span>Phone number</span><input bind:value={phone} autocomplete="tel" inputmode="tel"/></label><button class="primary" disabled={saving}><Save/> Save profile</button></form></article>
      <div class="security"><article><header><KeyRound/><div><h2>Change password</h2><p>Use a unique password you don’t use elsewhere.</p></div></header>{#if user.provider==="google"}<p class="provider-note">This account signs in through Google and does not have a Bengal Port password.</p>{:else}<form onsubmit={(e)=>{e.preventDefault();changePassword()}}><label><span>Current password</span><input type="password" bind:value={currentPassword} autocomplete="current-password" required/></label><label><span>New password</span><input type="password" bind:value={newPassword} autocomplete="new-password" minlength="8" required/><small>8+ characters with uppercase, lowercase and a number.</small></label><label><span>Confirm new password</span><input type="password" bind:value={confirm} autocomplete="new-password" required/></label><button class="primary" disabled={saving}><KeyRound/> Change password</button></form>{/if}</article>
      <article><header><ShieldCheck/><div><h2>Email two-factor authentication</h2><p>A one-time code is required after your password.</p></div><b class:enabled={user.twoFactorEnabled}>{user.twoFactorEnabled?"ON":"OFF"}</b></header>{#if user.provider==="password"}<form onsubmit={(e)=>{e.preventDefault();toggle2fa()}}><label><span>Confirm your password</span><input type="password" bind:value={securityPassword} autocomplete="current-password" required/></label><button class:danger={user.twoFactorEnabled} class="primary" disabled={saving}>{user.twoFactorEnabled?"Disable 2FA":"Enable 2FA"}</button></form>{:else}<p class="provider-note">Google protects this login. Manage two-step verification in your Google Account.</p>{/if}</article></div>
    </div>{/if}</div></section>
<style>
  .profile-hero{background:#143451;color:#fff;padding:clamp(3rem,8vw,5.5rem) 0}.profile-hero span{font-size:.72rem;letter-spacing:.15em;color:#dfb252;font-weight:800}.profile-hero h1{font-size:clamp(2.3rem,8vw,4rem);letter-spacing:-.045em;margin:.7rem 0}.profile-hero p{color:#d3dee6}.profile-page{background:#f3f5f5;padding:clamp(1rem,5vw,4rem) 0;min-height:35rem}.identity{display:flex;align-items:center;gap:1rem;background:#fff;border:1px solid #e0e5e7;border-radius:1rem;padding:1.2rem;margin-bottom:1rem}.avatar{width:3.8rem;height:3.8rem;flex:none;border-radius:50%;display:grid;place-items:center;background:#173955;color:#fff;font-size:1.4rem;font-weight:800;overflow:hidden}.avatar img{width:100%;height:100%;object-fit:cover}.identity h2,.identity p{margin:0}.identity p{color:#6b7c8b}.identity span{display:flex;align-items:center;gap:.3rem;font-size:.75rem;color:#397256;margin-top:.35rem}.identity span svg{width:.85rem}.identity>button{margin-left:auto;min-height:2.75rem;border:1px solid #dce1e3;background:#fff;border-radius:.65rem;padding:.6rem .8rem;display:flex;align-items:center;gap:.45rem;color:#526477}.settings{display:grid;gap:1rem}.settings article{background:#fff;border:1px solid #e0e5e7;border-radius:1rem;padding:clamp(1.1rem,4vw,1.7rem)}article>header{display:flex;align-items:flex-start;gap:.8rem;margin-bottom:1.25rem}article>header>svg{color:#b17d1c}article h2{font-size:1.1rem;color:#1c3b57;margin:0}article header p{font-size:.83rem;color:#748391;margin:.25rem 0 0}article header b{margin-left:auto;font-size:.65rem;letter-spacing:.08em;background:#edf0f1;color:#6f7b84;padding:.35rem .45rem;border-radius:.4rem}article header b.enabled{background:#e9f7ee;color:#267145}form{display:grid;gap:1rem}label{display:grid;gap:.4rem;font-size:.84rem;font-weight:700;color:#314b62}input{min-height:3rem;width:100%;border:1px solid #d5dddf;border-radius:.65rem;padding:.7rem .85rem;font:inherit;outline:none}input:focus{border-color:#bd8b29;box-shadow:0 0 0 .2rem rgba(198,150,54,.13)}input:disabled{background:#f3f5f5;color:#78858f}label small,.provider-note{font-size:.76rem;color:#7b8994}.primary{min-height:2.9rem;border:0;border-radius:.65rem;background:#173955;color:#fff;padding:.65rem .9rem;display:flex;align-items:center;justify-content:center;gap:.5rem;font-weight:800;cursor:pointer;transition:transform 150ms cubic-bezier(.23,1,.32,1),background-color 180ms ease}.primary:active{transform:scale(.98)}.primary.danger{background:#913d46}.notice{display:flex;align-items:center;gap:.5rem;padding:.8rem 1rem;border-radius:.7rem;margin-bottom:1rem}.notice svg{width:1rem}.success{background:#e9f7ee;color:#286a43}.error{background:#fff0f0;color:#91343e}.loading{text-align:center;padding:5rem;color:#6d7b86}.security{display:grid;gap:1rem}
  @media(min-width:48rem){.identity{padding:1.4rem 1.7rem}.settings{grid-template-columns:minmax(0,1fr) minmax(0,1fr)}}@media(hover:hover) and (pointer:fine){.primary:hover{background:#214965}.identity>button:hover{background:#f4f6f6}}@media(prefers-reduced-motion:reduce){.primary{transition-duration:.01ms}}@media(max-width:30rem){.identity{align-items:flex-start;flex-wrap:wrap}.identity>button{width:100%;justify-content:center;margin-left:0}}
</style>
